markers:
  lsec:
    - pecam1
    - cdh5
    - aqp1
    - stab2
    - lyve1
    - clec4g
    - mcam
    - kdr
    - eng
  hep:
    - alb
    - serpina1e
    - serpina1d
    - serpina3k
    - ahsg
    - cp
    - apoh
  stellate:
    - dcn
    - ecm1
    - gdf2
    - prelp
  kupfer:
    - clec4f
    - adgre1
